### ISSUE TITLE
No module named "common.custom_display"

### ISSUE THREAD

**Issue by Boufspiz** [cozplay/cozplay-demos#1]
File "C:\Users\Skyler\Downloads\Cozmo!\Games\Cozmogram.py", line 8, in <module>
    from common.custom_display import CustomDisplay
ImportError: No module named 'common.custom_display'

What's happening? Help...

**Comment by tso7** [comment]
You might have just downloaded the code for 'Cozmogram.py' script. You will also need a local copy of the 'common' module. You must download this and place it in the same root folder, which in your case would be : "C:\Users\Skyler\Downloads\Cozmo!"

The 'common' folder is available in the repository here:
https://github.com/cozplay/cozplay-demos/tree/master/common

**Comment by Boufspiz** [comment]
Well I had the 'common' folder but i never tried putting it anywhere. Thank
you so much! :)

>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
